release:
  github:
    owner: hemanjayam
    name: plax
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: cmd/plax/main.go
    id: plax
    binary: plax
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: windows
        goarch: arm64
    buildmode: 'c-shared'
  - main: cmd/plaxrun/main.go
    id: plaxrun
    binary: plaxrun
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: windows
        goarch: arm64
    buildmode: 'c-shared'
  - main: cmd/plaxrun/plugins/report/stdout/main.go
    id: plaxrun_report_stdout
    binary: plaxrun_report_stdout
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: windows
        goarch: arm64
    buildmode: 'c-shared'
  - main: cmd/plaxrun/plugins/report/octane/main.go
    id: plaxrun_report_octane
    binary: plaxrun_report_octane
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: windows
        goarch: arm64
    buildmode: 'c-shared'
  - main: cmd/plaxrun/plugins/report/rp/main.go
    id: plaxrun_report_rp
    binary: plaxrun_report_rp
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: windows
        goarch: arm64
    buildmode: 'c-shared'
  - main: cmd/yamlincl/main.go
    id: yamlincl
    binary: yamlincl
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: windows
        goarch: arm64
   buildmode: 'c-shared'
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - cmd/plaxrun/demos/**
      - demos/*
      - demos/*/*
      - doc/*.md
      - LICENSE
      - NOTICE
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
